language: php

php:
    - 5.6
    - 7.0
    - hhvm

before_install:
    - curl -s http://getcomposer.org/installer | php

install:
    - php composer.phar install

script: bin/phpunit

matrix:
  allow_failures:
    - php: hhvm
  fast_finish: true