language: php

php:
    - 5.6
    - hhvm

before_install:
    - curl -s http://getcomposer.org/installer | php

install:
    - php composer.phar install

before_script:
 - wget http://getcomposer.org/composer.phar
 - php composer.phar install --dev --no-interaction

script:
 - mkdir -p build/logs
 - php bin/phpunit -c phpunit-metrics-without-infrastructure.xml.dist --coverage-clover build/logs/clover.xml

after_script:
 - php bin/coveralls -v

matrix:
  allow_failures:
    - php: hhvm
  fast_finish: true