language: php

php:
    - 5.6
    - hhvm

before_install:
    - curl -s http://getcomposer.org/installer | php

install:
    - php composer.phar install

script:
    - mkdir -p build/logs
    - php bin/phpunit -c phpunit-metrics-without-infrastructure.xml.dist

after_success:
    - travis_retry php vendor/bin/coveralls

matrix:
  allow_failures:
    - php: hhvm
  fast_finish: true