language: php

php:
    - 5.6
    - hhvm

before_install:
    - composer self-update

install:
    - composer install

script:
 - mkdir -p build/logs
 - php bin/phpunit -c phpunit-metrics-without-infrastructure.xml.dist --coverage-clover build/logs/clover.xml

after_script:
 - php bin/coveralls -v

matrix:
  allow_failures:
    - php: hhvm
  fast_finish: true