#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';

use Symfony\Component\Console\Application;

$app = new Application('Console Tool', '1.0.0');
$app->add(new \Training\Infrastructure\UI\Console\Command\CreateUserCommand());
$app->run();